### ISSUE TITLE
Integrate Container generation into plattform/app instantiation

### ISSUE THREAD

**Issue by eichelbe** [iip-ecosphere/platform#10]
(Integrate) scripts for 
 - [x] Dockerfile
 - [x] Python requirements
 - [x] installed dependences YML file 
 - [x] container descriptor
 - [x] system dependencies to be installed -> bash, script creation and execution as part of Dockerfiles
 - [x] deployment of containers to registry
 - [x] setup information for container registry in configuration (authKey and registry as String [host:port], so far no tokens/certs)
 - [x] turn container constants into enum
 - [x] take up JAVA8 requirements if e.g., RTSA is installed -> must be in container and mentioned in installedDependencies.yml
 - [x] extend scripting for LXC integration
 - [x] deploy container descriptor to artifacts folder
 - [x] test container descriptor deployment to an absolute artifacts folder (may require EASy copy revision/fix)
 - [x] adjust ContainerManager (communicate with Luca Schulz for LXC) to take up Docker image name instead of filename/URL. Requires coordinates of container registry in DockerContainerManager in configuration, similar for LXC
 - [x] Adjust ecsRuntime.docker to pull container in addContainer if adequate
 - [x] Test in distributed test/evaluation environment #59 (@AhmadAlamoush)
 - [x] Document container creation in platform handbook section 6.5

**Comment by eichelbe** [comment]
Containers now go for appName/deviceContainerName/appVersion to separate between apps/devices. For now, ECSdevice enables container creation and has the container name "dflt". PLCnext if present would have "plcNext".

Ports for containers are a bit tricky:
 - By (current) default, ECSruntime and serviceManager may grab ay free port for AAS implementation server (in IVML aasImplServer.devicesAsEphemeral). While this is convenient for testing, it is a problem in a container because the port is determined at runtime and not exposed. For this purpose, the container descriptor has now one or two ports (ContainerType::Ecs_Svc_App, ecs and svcmgr as different processes in the same container) that are assigned by the service manager on startup. Pre-installed containers such as for ECSruntime have to care for determining iip.port and exposing it as part of the container installation on the device.
 - If aasImplServer.devicesAsEphemeral is false, aasImplPort in EcsDevice is consulted. If specified, that port will be taken, if not, it is by default aasImplServer.port. If ContainerType::Ecs_Svc_App, we need two ports. Here, the instantiation currently just takes the specified port (aasImplPort or aasImplServer.port) and adds 1 for the serviceManager port (iip.port.svgMgr).

**Comment by AhmadAlamoush** [comment]
The list is completed.
