### ISSUE TITLE
Document fixed data formats

### ISSUE THREAD

**Issue by eichelbe** [iip-ecosphere/platform#101]
in particular Yaml, of all parts of the platform

**Comment by eichelbe** [comment]
Inspired by @AhmadAlamoush I started a collection of the fixed formats employed by the platform. Currently, this is certainly not completed, rather than a starting point. E.g., the setup for the testing environment is not yet there/documented in tests/test.environment. Please feel free to contribute...

**Comment by AhmadAlamoush** [comment]
Documented in tests/test.environment.
