### ISSUE TITLE
Simplify platform installation

### ISSUE THREAD

**Issue by eichelbe** [iip-ecosphere/platform#111]
- [x] try installing platformDependencies in a single step 
- [x] use Mvn platform instantiator #109 with properties that can be set optionally from CLI
- [x] check / update github action script
- [x] update platform handbook, README.md, INSTALL.md
- [x] update installation slides

Cleanup moved to separate task for next release #115

**Comment by eichelbe** [comment]
@dzikaswinia @AhmadAlamoush The one-command install (`mvn install -Dunpack.force=true`) seems to be working. The old install shall be working, but the POM needs a shift of model-unpacking to generate-sources (via the extended IIP-Ecosphere unpack plugin) and as `src/main/easy` exists also `-Dunpack.force=true`. Explicit installation of `platformDependencies` is then not needed anymore.

I did not commit this so far as it may interfere with your efforts on #59 #102 #91, so I would need an "approval" ;)

**Comment by eichelbe** [comment]
@dzikaswinia @AhmadAlamoush after extending the IIP unpack plugin by a list of `initiallyAllowed` files, the `-Dunpack.force=true` is only needed to update the model. 

If you want to try it yourself, the patch for the POM is attached.
[install.zip](https://github.com/iip-ecosphere/platform/files/10155661/install.zip)

**Comment by AhmadAlamoush** [comment]
The installation slides are Updated.
