### ISSUE TITLE
Update service workshop material and provide videos

### ISSUE THREAD

**Issue by eichelbe** [iip-ecosphere/platform#118]
- [x] Update install slides (development container from dockerhub)
- [x] Check install slide for Java 8 -> Java 11 #35 (Ahmad)
- [x] Update service slides (use of development container, new build flows)
- [x] Motivation video (Holger)
- [x] Intro video (Chris)
- [x] Install video (explaining what and why, Ahmad)
- [x] Service implementation steps (Alex)
- [x] Short roundup, what else not discussed in this material (Holger)
- [x] X-Check
- [x] Summary, hand over to Anni (Holger)
- [x] Announce the videos, at least emails to service workshop participants (Chris)

**Comment by Chris-Sauer** [comment]
Announcement Mail with links to Videos, Slides, Platform handbook and GitHub Repository was send to all workshop participants
