### ISSUE TITLE
Fix /run issue in generated containers

### ISSUE THREAD

**Issue by eichelbe** [iip-ecosphere/platform#131]
PID-files cannot be created by platform services as run directory does not exist/is not writable. It's a warning but further scripts cannot rely on that. Please consider #130 which may bring in volume mappings of /run as well as [Plcnext](https://github.com/iip-ecosphere/platform/tree/main/platform/support/support.sysMetrics.plcnext) which requires /run mapped into the container. Also changing the default run directory in the configuration to /var/run or /tmp might be a solution, but may impact the container wrapper script.

**Comment by AhmadAlamoush** [comment]
It solved, the PID-files is created in /var/run directory inside of the container.
