### ISSUE TITLE
Handle numpy.datatypes in Python Serialization

### ISSUE THREAD

**Issue by eichelbe** [iip-ecosphere/platform#38]
- always/per default (performance?)
- on demand/flag in configuration
-> not in service code (as it is now)

**Comment by eichelbe** [comment]
To ease such integrations, shall we consider this as a default translation and just put it into generated code? Shall we enable it by default?

**Comment by JimmyAppel** [comment]
I would say the default should be exactly this, handeling the numpy data conversion in python. But I am not sure on how to add this into generated code as it would depend on the way the data gets returned from whatever AI method is used.

**Comment by eichelbe** [comment]
No worries, could you please copy the conversion code fragment here...

**Comment by JimmyAppel** [comment]
result.setWheelColour(inspection_resut["WheelColour"])
            result.setEngraving(inspection_resut["Engraving"].item())
            sys.stderr.write(">>>>>>>>>>>>VALUES_: " + str(type(inspection_resut["Engraving"])))
            result.setEngravingConfidence(inspection_resut["EngravingConfidence"].item())
            sys.stderr.write(">>>>>>>>>>>>VALUES_: " + str(type(inspection_resut["EngravingConfidence"])))
            result.setScratch(inspection_resut["Scratch"].item())
            sys.stderr.write(">>>>>>>>>>>>VALUES_: " + str(type(inspection_resut["Scratch"])))
            result.setScratchConfidence(inspection_resut["ScratchConfidence"].item())
            sys.stderr.write(">>>>>>>>>>>>VALUES_: " + str(type(inspection_resut["ScratchConfidence"])))
            result.setOneWindowConfidence(inspection_resut["OneWindowConfidence"].item())
            sys.stderr.write(">>>>>>>>>>>>VALUES_: " + str(type(inspection_resut["OneWindowConfidence"])))
            result.setTwoWindowsConfidence(inspection_resut["TwoWindowConfidence"].item())
            sys.stderr.write(">>>>>>>>>>>>VALUES_: " + str(type(inspection_resut["TwoWindowConfidence"])))
            result.setThreeWindowsConfidence(inspection_resut["ThreeWindowConfidence"].item())
            sys.stderr.write(">>>>>>>>>>>>VALUES_: " + str(type(inspection_resut["ThreeWindowConfidence"])))

**Comment by eichelbe** [comment]
Ok, as far as I can see, the code assumes that we have numpy datatypes. The generic code would not know implementation details. How could this then look like? Do we need some type checks using the default assignment as fallback?

**Comment by JimmyAppel** [comment]
Just to make sure: 
inspection result is a dictornary conataining any number of types in any combination depending on the reuslt the concrete AI script generates. 
result it the python implementation of the AIResult class that will be auto generated based on the usecase from an ivml to send the results back from python to java
What you want to do is to just make the AI script output the dictionary and then convert that via generated code in a way AIReuslt could transport it?

**Comment by eichelbe** [comment]
right, that was the idea, but it requires knowledge about the mapping between the internal variables and the generated result. 

1) One approach could be to provide an any-to-result field conversion taking into account numpy (if it is somehow used/imported). Would lead to some fixed functions for the base types and could be part of the service environment with the recommendation to use them (responsibility of service developer, offer by us). No need for code generation.

2) A second could be knowledge about which script variables, a kind of dictionary that links variables to setters and a function that processes that dictionary perfoming the conversion. A base version with references to the result can be generated and part of the "interface". Declaring the script part of the dictionary would be in the responsibility of the service developer, probably also the call to the processing function including a self-reference and the result instance.

3) ... no idea so far

Could you please try both versions out with some example code. Might be a 3) or 4) comes up. If not, we can select the most Pythonish way ;)

**Comment by JimmyAppel** [comment]
I can look into it, but for now it seems a bit overengineered if the other option is to just document: "If the reuslt returnes numpy datatypes converte these in the normal python datatyped bevore filling the AIReuslt class. " As the Dev. would need to adjust the ivml for AIResutl anyway to fit his result sheme. 
I mean the current approach is that the Dev. would have to edit the (in case of HM22) examplePythonService which provides him with the pyhton AI interfac and AIReuslt. 
Or do we want to change that into them jsut inputting a script that will be called from there to further ease integration?

**Comment by eichelbe** [comment]
This is the platform game - make life easier for others not knowing about internal details. RTFM... you will see with the service integration workshop. Of course, the counter question is whether there is a feasible solution at all or the final answer is RTFM. So the suggestion is to think about supporting solutions and to discuss them. It's not only about HM'22 but all cases that will follow with Python. If your last question is an approach, try it and we will discuss it...

**Comment by eichelbe** [comment]
Added 3) and 4) as further options...

**Comment by JimmyAppel** [comment]
Ok I implemented a solution. It seems like it will not result in a performance penalty.
I created a method which will take a value and the name of the value to be set in AIResultImpl (so the name used in the .ivml), check if it is a numpy data type, determine the correct setter of AIresultImpl and set the value. So nothing realy changed but the dev. would not need to think about return datatype.

**Comment by eichelbe** [comment]
Nice. Meas that we have to update the generation for the data types, or? Can you post your example code as a starting point?

**Comment by JimmyAppel** [comment]
self.setValueToAIResult(inspection_resut["EngravingConfidence"], "engravingConfidence", result)

    def setValueToAIResult(self, value, name: str, aiResult: AiResultImpl()):
        methodName = "set" + name[0].upper() + name[1:]
        setter = getattr(aiResult, methodName)
        if ("numpy" in str(type(value))):
            setter(value.item())
        else:
            setter(value)
This should also be committed in the ExampleService.py. As it stands we would not need to change anything on the generation side, as the names of the setters are already derived from the names of the variables. Only downside I see is, that one needs to use the correct name.

**Comment by eichelbe** [comment]
Ok, we can turn it into one special method per field through generation. This would solve the "problem" with the name. Let's assume <Name> is the name of the field and substituted by the generation. Similar attr as the field itself. Would this then work (instead of the existing setter) - called as result.setEngravingConfidence(inspection_resut["EngravingConfidence"])? I'm not sure about self and aiResult in your code...

set<Name>(self, value): 
    setter = getattr(self, "<Name>")
    if ("numpy" in str(type(value))):
        attr = value.item()
    else 
        attr = value

**Comment by JimmyAppel** [comment]
If we make this into the "default" setter method we could skip the "setter = getattr(self, "name")" as this is just a way to access the methods by string. If we generate this for each attribute we could just use the correct setter.

**Comment by eichelbe** [comment]
Right, so it would be that? That's surprisingly easy ;)

    set<Name>(self, value): 
        if ("numpy" in str(type(value))):
            attr = value.item()
        else 
            attr = value

**Comment by JimmyAppel** [comment]
This would be in the AIResult Class if I see this correctly, as it would take the place of the currently used normal setters, in this case self will not be needed if I got my pyhon knowledge right. 
So not much to change. 
 (Example from AIResultImpl from HM22)
    def setScratch(self, v : bool):
        self.scratch = v
We might need to remove the : <type> as this could lead to issues with the .item() as normal datatypes do not know this method I think.

**Comment by eichelbe** [comment]
hmm... then we miss the v.item() in case of numpy, or? Right, the type hint would not be helpful then. Would be mentioned in the documentation.

**Comment by JimmyAppel** [comment]
Oh yea, what I send was just how it looks now.
This would be how I think it should look and cloud work.
def set<name>(self, value):
  if ("numpy" in str(type(value))):
        self.attr = value.item()
  else:
        self.attr = value

**Comment by eichelbe** [comment]
Ok, first version in github. Does this apply to all basic Python types or just some selected such as int?

**Comment by JimmyAppel** [comment]
What applies? That they might have a numpy version?

**Comment by eichelbe** [comment]
the conversion... e.g., do we need it for strings?

**Comment by JimmyAppel** [comment]
No, the numpy types cover boolean, bytes, short, int, long, single, double, float. If im not mistaken that should be everything but strings.

**Comment by eichelbe** [comment]
indeed, found the same page. as a first try, we will limit the conversion to certain types and their array types (e.g., to avoid string). If more specific conversion code is needed then, we will have to modify these parts accordingly,

**Comment by eichelbe** [comment]
ok, considered, committed, building on CI. Could you please then give it a try when rewriting the HM'22 AI script to use only those new setters.

**Comment by JimmyAppel** [comment]
As my Syntax controll is now active I tested both commands on each of the Pythonscrips in the HM22. They cannot detect an issue and I am not seeing one. I would consider this issue to be resolved.
Further as I was looking into np.arrays to normal arrays: Python does not have normal arrays natively. The best possibility would be to use narray.tolist(). It depends what you need to convert it into a java array in the end.
