### ISSUE TITLE
Simplify build process for examples

### ISSUE THREAD

**Issue by eichelbe** [iip-ecosphere/platform#40]
already on the way :) 
- only one POM
- build.sh
- README.md
- platform handbook (add to Section 6.3)

impl.impl/impl.model
-> README.md
-> platform handbook (Section 6.4)

**Comment by eichelbe** [comment]
examples.vdw seems to be different/cause problems @AhmadAlamoush

**Comment by eichelbe** [comment]
Also Install (change handbook install and README.md accordingly), consider resources folder, synch with #22 to enable new authentication for broker @AhmadAlamoush

**Comment by eichelbe** [comment]
Further, can we have a Maven system property to define the name of the resources folder ("resources" vs. "resources.ipr") to switch on demand with "resources" as default, e.g., -Diip.resources=resources.ipr on the Maven command line @AhmadAlamoush

**Comment by eichelbe** [comment]
JFYI, upgraded hm22 build process to maven profiles

**Comment by eichelbe** [comment]
Question: Shall we stay with "Example"/"EasyGen" for the profile names or - thinking about the service workshop - uniformly switch to "App"/"EasyGen"...

**Comment by eichelbe** [comment]
In some cases an explicit default profile may be helpful (must not be in all cases): https://stackoverflow.com/questions/11824328/default-build-profile-for-maven

**Comment by AhmadAlamoush** [comment]
> examples.vdw seems to be different/cause problems @AhmadAlamoush Jenkins does not run the code as regression test, because it is not allowed to contact VDW Umati (in discussion with Uwe/RZ). Thus, difficult to keep eye on. Bug #60 fixed.

examples.vdw is completed

> impl.impl/impl.model? @AhmadAlamoush 

Completed

**Comment by AhmadAlamoush** [comment]
> Question: Shall we stay in the POM files with "Example"/"EasyGen" for the profile names or - thinking about the service workshop - uniformly switch to "App"/"EasyGen"...

Completed

**Comment by AhmadAlamoush** [comment]
> Further, can we have a Maven system property to define the name of the resources folder ("resources" vs. "resources.ipr") to switch on demand with "resources" as default, e.g., -Diip.resources=resources.ipr on the Maven command line @AhmadAlamoush

Completed, Update the pom.xml file for examples.python, examples.KODEX, examples.rtsa, and examples.vdw to have a default value for iip.resources (which is resources) and allow to pass new value by adding (-Diip.resources="NewFolderName") to the command.

**Comment by eichelbe** [comment]
Cool. Did you mention that already in the README.md? Can you write a short paragraph for the platform handbook explaining the unified build commands and their options (such as -Diip.resources) - as a summary of Section 6.4 where you already updated the figure?

**Comment by eichelbe** [comment]
As discussed yesterday
