### ISSUE TITLE
Is there a tensor flow inference-only Python package

### ISSUE THREAD

**Issue by eichelbe** [iip-ecosphere/platform#49]

**Comment by JimmyAppel** [comment]
Currently it does not seem likely. As far as I can tell there is no real way to reduce the TF size through compiling yourself. When searching for this case online TFlite comes up very often. It is said to be less performant by around 0-4% but the acutall value will varay based on the task at hand.
There might be ways I have yet to find (compiling the C version and calling that?) but as my first try to compile myself failed and I still do not know what exactly went wrong, I put off that task for now.

**Comment by eichelbe** [comment]
Krishna is working on RAM
