### ISSUE TITLE
Document example models

### ISSUE THREAD

**Issue by eichelbe** [iip-ecosphere/platform#54]

**Comment by eichelbe** [comment]
Could you please add parts of the prepared documentation (pptx and pdf) to examples.KODEX, examples.rtsa and examples.python. For the graphical style, please see configuration.configuration/src/test/easy/summary.pptx. Please link then the respective PDF from the README.md of the individual example projects.

**Comment by eichelbe** [comment]
Thanks... nice.

Could you please turn the links in README.md into real links and move the slides into an own docs folder... the resources folder is for resources to be included by the automated integration into the services artifact. And, could you please add similar foles to examples.vdw (now a real application graph rather than just a connector). 

May be afterwards @AhmadAlamoush can add some of his explaining slides on the models etc.

**Comment by Chris-Sauer** [comment]
README.ms links fixed, slides moved to new "docs" folder for each example. Working on the examples.vdw silde(s) now.

**Comment by eichelbe** [comment]
As discussed, KODEX needs update due to DB upgrade. You may close the task, you may also close it after the KODEX doc update.

**Comment by Chris-Sauer** [comment]
Task closed, Documentation for all examples integrated.

**Comment by eichelbe** [comment]
The console and broker issue. Please have a look at examples.pythonSync

**Comment by Chris-Sauer** [comment]
Updated examplesPythonSync slides and the readme

**Comment by eichelbe** [comment]
Why updating examples.pythonSync - that was ok (based on the discussion of last weak), and now has examplePython and examplePythonSync in the doc folder?
Please check/update
- [ ] examples.python
- [ ] examples.vdw
- [ ] example.rtsa
- [ ] and now also examples.pythonSync

**Comment by Chris-Sauer** [comment]
Updated the slides to all for examples
