### ISSUE TITLE
Remove user/password/keystore from transport in model/code

### ISSUE THREAD

**Issue by eichelbe** [iip-ecosphere/platform#58]
depends on #22

**Comment by eichelbe** [comment]
Check documentation in README.MD

**Comment by eichelbe** [comment]
Done for connectors. @AhmadAlamoush Before cleaning up transport component/projects, please check K8S parts on use of username/passwords/keystores. If identityStore is not used, please change to identityStore and pass task back to me.

**Comment by AhmadAlamoush** [comment]
I have changed K8S to use identityStore.
I have updated Install and examples.vdw to use identityStore.

**Comment by eichelbe** [comment]
Thanks... continuing the cleanup

**Comment by eichelbe** [comment]
Removed usernames/passwords/keystore locations etc. from model and platform code -> Use IdentityStore instead, further plugins may be provided.
