### ISSUE TITLE
Turn JSON monitoring structures in AAS to Double/Integer with semanticId.

### ISSUE THREAD

**Issue by eichelbe** [iip-ecosphere/platform#63]
initial solution, intended to contain the unit and the description. Either we turn this into AAS structure or a simple double value with associated semanticId (multi-language description may be added). 

- Prepared in platform. Currently, switched off, i.e., presented as usual.
- Update of Mgt UI required. Would be good to read out structure if type is string, value only if type is Double. If there is a semanticId IRDI, take over unit/description from IRDI/ECLASS.

**Comment by eichelbe** [comment]
as basis: semanticId resolution from #68 and AAS operation defined there

**Comment by eichelbe** [comment]
As suggested by @ChrisKHil switched in platform code to numeric values with semanticIds.

**Comment by eichelbe** [comment]
At least values are still there. No units/semantic ids.

**Comment by eichelbe** [comment]
BTW, please adjust the colors for device display to increase readability.

**Comment by eichelbe** [comment]
Added Monika, we discussed the semanticId resolution some weeks ago...

**Comment by dzikaswinia** [comment]
Mgt UI updated - displaying value, unit and semantic Id.
