### ISSUE TITLE
Check examples.KODEX for fluctuating "_"

### ISSUE THREAD

**Issue by eichelbe** [iip-ecosphere/platform#66]

**Comment by eichelbe** [comment]
Strange Vodoo... first no "_", with -U generate-sources there it is. No compile error. Maven update, ups there it is. Trying to "convince" Jenkins. Then it's your turn.

**Comment by eichelbe** [comment]
a bit console mvn update on Jenkins, now running through with "_". Strange, very strange.

**Comment by eichelbe** [comment]
some warn that code with "_" may be broken as it initiates Java Vodoo, others just say it's a matter of style and consistency, but not of function. Very strange. Even VIL toIdentifier allows $kip and _kip to pass without modification. Trying to sharpen the identifier translation in the code generation just that whitespaces come around... then, problably, close the issue.

**Comment by eichelbe** [comment]
identifiers change ran through, examples still running... closing this issue

**Comment by Chris-Sauer** [comment]
Okay, will check locally

**Comment by eichelbe** [comment]
Strange thing... after Eclipse restart the compile problem was back. After full Maven build with -U, Eclipse close/reopen project it was gone again.

**Comment by Chris-Sauer** [comment]
The latest changes +Maven building with -U solved the issue for my locale instance

**Comment by eichelbe** [comment]
Happened again after a Maven update of another project :/ Same game, ran generation, closed Eclipse project, re-opened it, gone. Tried to cleanup outdated Maven snapshots with MvnCentral->CleanMvnSnapshots. Let's see whether the ghost comes back.

**Comment by Chris-Sauer** [comment]
Pulled latest changes, Eclipse restart, recompiled with -U, installed with -U, no problems, example runs without problem.

**Comment by eichelbe** [comment]
Good news, thanks :)
