### ISSUE TITLE
Revise platform installation guidelines

### ISSUE THREAD

**Issue by eichelbe** [iip-ecosphere/platform#69]

**Comment by eichelbe** [comment]
-> Installation guideline
-> Slides
-> Platform Handbook

**Comment by Chris-Sauer** [comment]
Installation guideline slides for Windows and Linux revised, updated and commited as Pdfs under "platform/documentation/"

**Comment by eichelbe** [comment]
Please also commit the sources to github - please tick sub-task.
Please check/revies the platform handbook if needed - if not, please tick sub-task.
If done, please close task.

**Comment by Chris-Sauer** [comment]
Installation guides were reviewed and are available
