### ISSUE TITLE
UI: Progress reporting

### ISSUE THREAD

**Issue by eichelbe** [iip-ecosphere/platform#70]
Uptake of #67
Working so far
- [x] consider endpoint from status AAS -> port/path/URL may change through configuration
- [x] check whether adding/removing artifact is now reflected with taskId

**Comment by eichelbe** [comment]
@ChrisKHil The AAS containing the deployment plan operations shall now have deployPlanAsync and undeployPlanAsync, both returning a taskId. This taskId shall be passed along with the StatusMessages for this task. The task status can be obtained from the AAS via getTaskStatus(taskId)... I missed resetting the task status. Will be committed next.

**Comment by ChrisKHil** [comment]
Progress should be should at the bottom of the UI. Unfortunately I could not test if this works as intended. Verificvation needed

**Comment by eichelbe** [comment]
Thanks. We will check this as soon as the new UR-PLC is validated and the application can be completely started on the demonstration devices.

**Comment by eichelbe** [comment]
refined status tracking is on the way...

**Comment by eichelbe** [comment]
working...
