### ISSUE TITLE
Test examples with MQTT

### ISSUE THREAD

**Issue by eichelbe** [iip-ecosphere/platform#71]
See platform handbook for model change
automatic (in regression) or manual

**Comment by AhmadAlamoush** [comment]
When starting the platform, it shows the following error :
"Cannot create transport connector: Unable to connect to server"
"No transport setup, will not listen to trace records."

**Comment by eichelbe** [comment]
Tried with examples.pythonSync and MQTTv3. Fixed generation of application.yml, runs with generated MQTT broker on Windows, fails on Linux with similar problem - connect timed out.

**Comment by eichelbe** [comment]
It could be a different setup of the protocols. The MQTT tests operate with actionTimeout=3000 while AMQP uses the default 1000 ms. So far, this is not reflected in the configuration. May also be that some other setup of broker/protocol, e.g., in the K8S experiments is missing...

**Comment by eichelbe** [comment]
Indeed, it was the actionTimeout, at least for examples.pythonSync. Default for MQTT is now at least 3000 ms. examples.pythonSync now running with MQTT v3.
