### ISSUE TITLE
Review platform handbook (v0.4.0)

### ISSUE THREAD

**Issue by eichelbe** [iip-ecosphere/platform#78]
Als usual, critical review of the "green" parts (can be done incrementally).
TddT'22 parts still missing.
The usual way, changed-tracked word file as copy of the original in the SVN.

**Comment by AhmadAlamoush** [comment]
Review is completed "PlatformHandbook-0.02-SNAPSHOT-V0.4_Ahmad.docx"

**Comment by eichelbe** [comment]
Integrated into 0.0.3 in SVN.

@Chris-Sauer if there are further suggestions, please add them to the version of Ahmad with change tracking.

**Comment by Chris-Sauer** [comment]
Finished my review, as "PlatformHandbook-0.02-SNAPSHOT-V0.4_Ahmad_Chris.docx"

**Comment by eichelbe** [comment]
Thanks. Integrated in SVN.
