### ISSUE TITLE
UI: Add/check UI failure message if AAS is not reachable.

### ISSUE THREAD

**Issue by eichelbe** [iip-ecosphere/platform#82]
Stems from IP/instantiation problems. UI still quiet not showing information about problem. May also be related to my browser (Chrome, Linux).

**Comment by ChrisKHil** [comment]
UI displays the error message of the failed http reequest, which is unfortunately not very expressive. Additionaly hint to check cors unblocker is shown (until cors problem is resolved)

**Comment by eichelbe** [comment]
Ok, then let's close this issue.
