### ISSUE TITLE
UI: Display platform build information

### ISSUE THREAD

**Issue by eichelbe** [iip-ecosphere/platform#85]
The fields from the Platform submodel/technical submodel to have version/build id/vendor available.

**Comment by ChrisKHil** [comment]
/aas/submodels/TechnicalData/submodel contains fields version but does not contain build id or vendor. 

Maybe the submodel is wrong? Clarification needed

**Comment by eichelbe** [comment]
Was a submodel built (by the ECSruntime)? Could you please send me the logs by mail?

**Comment by ChrisKHil** [comment]
version and build id are now displayed in the header
